DROP INDEX IF EXISTS usr_idx;
DROP INDEX IF EXISTS usr_email_idx;
DROP INDEX IF EXISTS usr_role_idx;

DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS team_record;
DROP TABLE IF EXISTS division;
DROP TABLE IF EXISTS tour;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS league;

DROP TABLE IF EXISTS sport_counting;
DROP TABLE IF EXISTS counting;
DROP TABLE IF EXISTS sport;

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS uperm;
DROP TABLE IF EXISTS usr;


DROP SEQUENCE IF EXISTS league_seq;
DROP SEQUENCE IF EXISTS team_seq;
DROP SEQUENCE IF EXISTS div_seq;
DROP SEQUENCE IF EXISTS tour_seq;
DROP SEQUENCE IF EXISTS game_seq;
DROP SEQUENCE IF EXISTS perm_seq;
DROP SEQUENCE IF EXISTS user_seq;
DROP SEQUENCE IF EXISTS role_seq;
